site_name: ARP
site_url: https://github.com/ramp-eu/arp
repo_url: https://github.com/ramp-eu/arp
site_description: RAMP Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - Home: 'README.md'
  - Architecture : 'architecture.md'
  - 'User & Programmers Manual':
    - 'Getting started' : 'getting-started'
    - 'User Guide': 'usermanual.md'
    - 'API' : 'api.md'
  - Installation Guide: 'installationguide.md'