site_name: ARP
site_url: https://github.com/ramp-eu/arp
repo_url: https://github.com/ramp-eu/arp
site_description: RAMP Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - Home: 'README.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'API' : 'api.md'
    - 'User Guide': 'usermanual.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'installationguide.md'